### ISSUE TITLE
Password generator Chart does not update

### ISSUE THREAD

**Issue by Flamifly** [FrozenAssassine/EasePass#124]
If i change the Password the Chart does not update
![image](https://github.com/user-attachments/assets/e9ec142b-cea2-4825-8145-f89df5fa1fec)

**Comment by Flamifly** [comment]
can be fixed for example like https://github.com/Flamifly/EasePass/commit/fd362afa8f8022b98080b7c865bf19e1d72d46aa
By that the Char will be updated everytime the Text changed (TextChanged event which calls EvaluatePassword)

**Comment by Flamifly** [comment]
I also have seen that the "Seen before" part of the Chart does not check if the Passwort has already been used before
Does this work different as I expect?

**Comment by FrozenAssassine** [comment]
Fixed in #125 merge will be soon. Again thanks for your help here ❤️

**Comment by Flamifly** [comment]
Your welcome👍

I commented my guess why it checked if the Password exist twice in #125
