### ISSUE TITLE
App title is wrong

### ISSUE THREAD

**Issue by FrozenAssassine** [FrozenAssassine/EasePass#13]
![image](https://github.com/FrozenAssassine/EasePass/assets/72889252/311558f5-3938-4a80-8c18-6642490d9c1f)

**Comment by finn-freitag** [comment]
Title is easy `Title="Ease Pass"` in `MainWindow.xaml`, but the icon seems a bit annoying: [https://github.com/microsoft/microsoft-ui-xaml/issues/4056](https://github.com/microsoft/microsoft-ui-xaml/issues/4056).
