### ISSUE TITLE
Functionality to return from Password

### ISSUE THREAD

**Issue by Flamifly** [FrozenAssassine/EasePass#138]
If I click on a Password I can't exit it anymore

I would expect that I could return from the Password to the empty Main Screen.
If that is hard to implement I would automaticly open the first Password so the Main Screen is newer empty

**Comment by FrozenAssassine** [comment]
It should not be hard, just show/hide the password show area. I will try to figure this out tomorrow:

```passwordShowArea.Visibility = Visibility.Collapsed;```
