### ISSUE TITLE
QR-Code scanning for 2FA

### ISSUE THREAD

**Issue by finn-freitag** [FrozenAssassine/EasePass#14]

**Comment by finn-freitag** [comment]
Just the minimize, maximize and close buttons needs to be deleted from ScreenScannerWindow for a better look. Hope anyone can help.

**Comment by FrozenAssassine** [comment]
I will try to remove them, but It seems only kind of possible.

**Comment by FrozenAssassine** [comment]
Actually, it is very simple to hide the caption buttons, here is the code. I will implement it into the branch:

```cs
var presenter = this.AppWindow.Presenter as OverlappedPresenter;
presenter.IsMaximizable = false;
presenter.IsMinimizable = false;
```
