### ISSUE TITLE
BCrypt does not target .Net

### ISSUE THREAD

**Issue by Flamifly** [FrozenAssassine/EasePass#146]
I get an Warning for the BCrypt Package that it does not target .Net and it only target .Net Framework

Should this be changed?
It could be changed to https://github.com/BcryptNet/bcrypt.net

**Comment by FrozenAssassine** [comment]
Well it worked for now haha, but it should not make a problem to update, would prop. be better.

We currently use it only to support older database versions from the early times of Ease Pass, not really in real use anymore.

**Comment by Flamifly** [comment]
If it's just used to support older version i would not update because not sure if it would do some stuff different
And if it is not used anymore how you hash the Passwords at the moment?

**Comment by finn-freitag** [comment]
We don’t hash passwords. Instead, we encrypt the database using the password provided by the user. If decryption during login fails, it’s clear the user’s password was incorrect. This approach eliminates the need to store database passwords, even in a hashed form.
