### ISSUE TITLE
Duplicate Implementations to OOP Implementation

### ISSUE THREAD

**Issue by Flamifly** [FrozenAssassine/EasePass#147]
This Ticket is about removing Duplicate implementations to an OOP Concept Implementation

Example of Duplicates:
![image](https://github.com/user-attachments/assets/2024ba84-964f-42b0-b692-4cdc8a36ab0c)
(I know some of them Change but they repeat after a While on the Sorting Helper)

I will change that tomorrow or at the Weekend

**Comment by FrozenAssassine** [comment]
Oh let me fix this real quick, this is actually pretty bad code @finn-freitag 😂😘

**Comment by Flamifly** [comment]
Not quite sure but aint there another way how to do that once?
![image](https://github.com/user-attachments/assets/e3381dcd-a6b5-4b51-a702-344887be55e0)

Maybe one of you know how Database.ReadFile

**Comment by FrozenAssassine** [comment]
I think I found a simpler way which reduced the number of returns to two. I committed to master!
