### ISSUE TITLE
Portable version for USB-Stick

### ISSUE THREAD

**Issue by finn-freitag** [FrozenAssassine/EasePass#15]

**Comment by FrozenAssassine** [comment]
https://www.youtube.com/watch?v=CotNgFCnoj4

**Comment by FrozenAssassine** [comment]
I have added the configuration in the csproj file, but it still has an error when running.
I've made a branch for it.

![image](https://github.com/FrozenAssassine/EasePass/assets/72889252/14fe5d0d-95de-4d9b-9a8c-d0527b71edce)

**Comment by finn-freitag** [comment]
It should also recognize if it's running in portable version or not to save the data next to the application (for example on USB-Stick) and not in the AppData folder. An alternative is to create a setting.

**Comment by FrozenAssassine** [comment]
At the current state not really possible so closing this for now.
