### ISSUE TITLE
File/Directory Methods

### ISSUE THREAD

**Issue by Flamifly** [FrozenAssassine/EasePass#151]
I would like to create a class which contains basic File or Directory that is currently used for example the Logic on the Database to check if a File has a given extension

I would not expect it to be there so were would be a good place for Such classes?

Extensions, Helper or in a New IO Folder?

**Comment by FrozenAssassine** [comment]
Good idea...

I guess if it is a static class, put it in Helper folder.

**Comment by FrozenAssassine** [comment]
I think you implemented this in #152 if not done yet, feel free to reopen
