### ISSUE TITLE
Create Database Dialog does not show Error

### ISSUE THREAD

**Issue by Flamifly** [FrozenAssassine/EasePass#156]
If I want to create a new Database the Dialog does not tell me that I have two different Passwords if I click on create
![image](https://github.com/user-attachments/assets/5aa6cc6e-15a1-4389-a68b-498af43ae6a8)

**Comment by Flamifly** [comment]
Same at changing the Password
![image](https://github.com/user-attachments/assets/c21d4f39-ce5a-4ff3-a7a5-009f152443e9)

At least there occure some Messages in the Background

**Comment by Flamifly** [comment]
I will take a look at the creating Database at the moment

**Comment by Flamifly** [comment]
If I try to close the Dialog without having same Passwords it is not possible

**Comment by Flamifly** [comment]
Now;
![image](https://github.com/user-attachments/assets/38339e1c-91b7-4ef7-b591-730ad4569272)

**Comment by Flamifly** [comment]
Closing works now too

**Comment by FrozenAssassine** [comment]
Well done, looks very good👍
