### ISSUE TITLE
Save the current app state (minimized/maximized)

### ISSUE THREAD

**Issue by FrozenAssassine** [FrozenAssassine/EasePass#16]

**Comment by finn-freitag** [comment]
Let's just use my commit, it does nearly the same.

**Comment by FrozenAssassine** [comment]
There is one problem with your code and that is multi monitor support. 
Imagine I open the app at my third monitor, let it be position 3500|1300, then I close the app and the position will be saved. When I turn off that monitor and open the app again, the app will recover its position, but you won't see it, becasue the monitor is not there anymore.
