### ISSUE TITLE
Don't allow database creations without entering a path

### ISSUE THREAD

**Issue by FrozenAssassine** [FrozenAssassine/EasePass#160]
When entering no path in the database create dialog, it still lets you create the database, but you will always get errors, that the database could not be saved.

Also only allow database with passwords longer than 3 characters like in register page.

**Comment by Flamifly** [comment]
register page is 4 characters
You work on that already?

**Comment by FrozenAssassine** [comment]
I will have a look at it now 👍

**Comment by Flamifly** [comment]
Reviewed your commit:
I am not sure if the InvalidDatabasePath with showMainWindow: true is even possible.
I tested it I think as I implemented it and everything crashed I think.
If that's the case you probably should remove the showMainWindow param to prevent this Happen by accident calling it with true

**Comment by FrozenAssassine** [comment]
Wait, but don't all of those by default show on the main page, so this should either, if I want to? I am confused 😂

**Comment by Flamifly** [comment]
No no let me explain

Before my change the InfoMessages could only be shown in the MainWindow because the InfoBar extension always added it to the Children of the MainWindow.

I thought I don't care if it will be shown there so I just passed my InfoBar and I got an Exception (if I remember it right)
So I implemented the "showMainWindow" Parameter in the Extension to be able to turn it so I do not get an exception

I don't know if you meant that but WPF does not show it on the MainWindow on his own it was in the extension implemented

**Comment by Flamifly** [comment]
I will force this error real quick

**Comment by Flamifly** [comment]
![image](https://github.com/user-attachments/assets/5f7451dc-0e55-4e3c-a219-2f280f33f291)

**Comment by FrozenAssassine** [comment]
Ahh, I will have a look. 

Btw it is not WPF, but WinUI3

**Comment by Flamifly** [comment]
What is the differences between WPF and WinUI?

If you found a Solution could you tell me what was wrong?

**Comment by FrozenAssassine** [comment]
The key difference between WPF and WinUI is probably the overall design of the UI. New and good looking UI elements and controls. WinUI is simply newer then WPF.

**Comment by FrozenAssassine** [comment]
Ok I got it working. 
You can check out the commit in #169 

So you already added the Infobar to the Dialog and only replaced its content.
I changed that and added a StackPanel to the Dialog. The StackPanel gets passed to the following function in the infoBarExtension.cs file:

```cs
private static void AddInfobar(Panel parent, InfoBar infobar)
{
    if (parent == null)
        MainWindow.InfoMessagesPanel.Children.Add(infobar);
    else
        parent.Children.Add(infobar);
}
```

As you can see, in the function above I pass the Infobar and a parent variable.
The parent variable is the Stackpanel of the dialog. If the StackPanel is provided, the Infobar gets added to the Stackpanel as a children. Otherwise, it renders on the MainWindow like normal.

Does this make sense?

**Comment by Flamifly** [comment]
Is it possible to Add the InfoMessage to the MainWindow and the Dialog?

**Comment by FrozenAssassine** [comment]
Only if you duplicate the InfoBar. Should not be hard to do, but is it really necessary?

By duplicate I mean, copy the needed properties like title, text, etc. to a new instance of InfoBar.

**Comment by Flamifly** [comment]
No it is necessary

**Comment by FrozenAssassine** [comment]
Oh did you mean simultaneously or just that I can add it sometimes to a ContetnDialog and some times to the MainWindow?

If not simultaneously it obviously will totally work!

**Comment by Flamifly** [comment]
Yea I meant simultaneously.
It does that in some way at the Change Password Dialog for the Databases (did not check that because I didn't care about it
