### ISSUE TITLE
On very first start, the language is system default, but after going to settings it is english

### ISSUE THREAD

**Issue by FrozenAssassine** [FrozenAssassine/EasePass#161]
When I start the software after deleting all its data, the language is default to German, because of my system. But when I then enter settings, the language combobox is still selected to english. By leaving settings, the language will also change. You default language then is english

**Comment by Flamifly** [comment]
Is someone working on that already?

You could use CultureInfo.InstalledUICulture.IetfLanguageTag; as default language or you could check if the language of the System exist if not use default

**Comment by Flamifly** [comment]
If no one is working on it I could do it

**Comment by FrozenAssassine** [comment]
Mostly if I work on it, I add the assignees tag, so everyone know 👍

**Comment by Flamifly** [comment]
Is there a Function to check if Translations for a Language exist?

**Comment by FrozenAssassine** [comment]
You could check whether the translation is in the LanguageList.resw file. I already have a function that iterates through the languages in that file to show them in the combobox. But I don't know a better approach if you mean that.

**Comment by Flamifly** [comment]
No I meant your first thing.
I will might check if I can fix it

**Comment by Flamifly** [comment]
Can you tell me the Class where the method exist?

**Comment by FrozenAssassine** [comment]
In Helper -> LocalizationHelper there is a variable called languages. It stores all the languages available. So in our case en-US & de-DE

**Comment by FrozenAssassine** [comment]
@Flamifly did you already start working here or can I fix this issue?

**Comment by Flamifly** [comment]
You can fix it I will go to sleep
If you won't fix it I will do it tomorrow

**Comment by FrozenAssassine** [comment]
Ok, gn😴

**Comment by Flamifly** [comment]
Good night
