### ISSUE TITLE
Regenerate Password closes Dialog

### ISSUE THREAD

**Issue by Flamifly** [FrozenAssassine/EasePass#165]
Is there a reason why we close the Dialog if we want to generate a new Password on the generate Password dialog?

It would be way faster if we would just change the password text (Closing and Opening the Dialog takes some time and loading everything in the Dialog

Maybe it was implemented this way because it did not update the chart in the past

**Comment by FrozenAssassine** [comment]
Exactly that was the case, do you have a better way?

**Comment by Flamifly** [comment]
I would do it this way https://github.com/Flamifly/EasePass/tree/Regenerate-Password
The Dialog does not close anymore and changes the Password by itself the Chart is loaded fast.
The only thing that takes long is generating the Password

**Comment by Flamifly** [comment]
I will check later if the generating Password could be improved

**Comment by FrozenAssassine** [comment]
Can you create a PR from that, so I can have a look at it?

**Comment by Flamifly** [comment]
Yea wait

**Comment by FrozenAssassine** [comment]
fixed in #167

**Comment by FrozenAssassine** [comment]
I also added a progress bar, which was already implemented, but not visible due to WinUI3 bug in the older version. The bug seems solved now 👍
