### ISSUE TITLE
Caching throws errors by clicking on show on the Password

### ISSUE THREAD

**Issue by Flamifly** [FrozenAssassine/EasePass#166]
If you click multiple Times on the Show Password button the GetSize Method for the cache throws an error
![image](https://github.com/user-attachments/assets/437e9d7a-a47f-40db-9489-25006b48decf)

The File does not exist at the moment is that on purpose?

**Comment by Flamifly** [comment]
Nevermind this error will be thrown by the Icon of the Passworditem

**Comment by FrozenAssassine** [comment]
If you mean this button, I can not reproduce this atm 
![image](https://github.com/user-attachments/assets/a7221a11-f55e-4bf4-b770-4827d9276c2d)

**Comment by Flamifly** [comment]
No it was wrong what I said.

If I have in the Website https://x the caching thrown the Error if I want to see an Icon

**Comment by Flamifly** [comment]
After I deactivated the Show Icons functionality it worked so I think it was the Website Icon

**Comment by FrozenAssassine** [comment]
But this should not happen, so when the user enters an invalid website, this thing throws exceptions. This is a pretty bad UX.

**Comment by Flamifly** [comment]
Do you know if the exception will be catched?

**Comment by FrozenAssassine** [comment]
I don't think so, but had no chance to investigate further so not sure.

**Comment by Flamifly** [comment]
No need to change
