### ISSUE TITLE
Open .epdb files directly by clicking on them in Windows explorer 

### ISSUE THREAD

**Issue by FrozenAssassine** [FrozenAssassine/EasePass#168]
Let's add an open with connection for .epdb files to Ease Pass. So the user can click a database file on his PC to show it directly in the app

**Comment by Flamifly** [comment]
You want Feedback if that's a good idea?

**Comment by FrozenAssassine** [comment]
Exactly, what do you think?

**Comment by Flamifly** [comment]
So if I understand it right you want to open a File with EasePass and the User should access every Password inside it?

**Comment by FrozenAssassine** [comment]
Yeah, when I have multiple databases laying in some folder on Windows and I double click a file, it should open, but then I am not sure about some things:

When the user opens a file, does this mean he only opens it read-only, or it directly gets imported as database or is it a one-time thing. With one time thing I mean, that the user can read and write, but it does not get saved to the added databases.

**Comment by Flamifly** [comment]
I would say:
- User Open File
- User enter Password
- User can see every PasswordItem in the File
- Users close the App and the PasswordItems are gone (I Do not mean that the File should be deleted or edited)

I would say it should be a one time thing.
But there could be a open for importing or adding the Database to my Password Manager.

In my Opinion it shouldn't be a Part of it until a User explicit want it

**Comment by Flamifly** [comment]
What happens at the Moment if the Path to the Password File does not exist anymore?

**Comment by FrozenAssassine** [comment]
Yeah I think your solution sounds the best. I will start implementing this.

I never tested what happened, but let me do so.

I figured out the following:
- If you delete the database while it's open, nothing happens, the file will be recreated.
- If you delete the database while it is not loaded, the choose Database box is empty and the database not visible anymore. So the app checks whether the file exist and if it doesn't it does not show.
