### ISSUE TITLE
Ability to store encrypted files or messages

### ISSUE THREAD

**Issue by FrozenAssassine** [FrozenAssassine/EasePass#17]

**Comment by finn-freitag** [comment]
Maybe we could just add an "Add file"-button to the "Notes" textbox. But I wouldn't overuse it.
![grafik](https://github.com/FrozenAssassine/EasePass/assets/126865059/8dfac875-907a-48e0-8e75-59dc1dba1826)

**Comment by FrozenAssassine** [comment]
This could be useful when having recovery codes in a file

**Comment by finn-freitag** [comment]
I also think it's useful and we should implement it. But why do you need recovery codes stored in your password manager when you are storing your credentials in the same password manager? If it's broken, they're both gone. But nevertheless it's useful for other things.

**Comment by FrozenAssassine** [comment]
LOL, didn't think about that 😂

**Comment by FrozenAssassine** [comment]
Not easy to implement, and would result in long loading times for the database. So closing this.
