### ISSUE TITLE
Add advanced button to Register Page

### ISSUE THREAD

**Issue by FrozenAssassine** [FrozenAssassine/EasePass#171]
Maybe some users directly want to enter the path of the database etc. So there should be a button for the advanced CreateDatabaseDialog setup, maybe also a hyperlink as you can see in the image provided?

![image](https://github.com/user-attachments/assets/bcee4911-ee37-4313-bd14-40dde8f44d74)

**Comment by Flamifly** [comment]
You mean entering Path where the Database should be created at,

**Comment by FrozenAssassine** [comment]
Yeah kind of, currently you are only able to create the database to the default location which is in C:\Users\bla\Appdata\Local\Packages\...

But maybe someone wants to create the database in a different location and maybe he also wants to enter a name or similar. So I would like to have an option where the CreateDabaseDialog directly opens up.
