### ISSUE TITLE
Generating Password

### ISSUE THREAD

**Issue by Flamifly** [FrozenAssassine/EasePass#174]
Is there a reason why we can disable some Charakters in the generated Password?

**Comment by FrozenAssassine** [comment]
Do you mean this thing in the settings?
This is because some users may not want some characters. So it's up to them what the password generator uses.

![image](https://github.com/user-attachments/assets/4f18f8dd-3849-4ea4-a6ad-c95a78e1ba5c)

**Comment by Flamifly** [comment]
Yea I meant this

**Comment by FrozenAssassine** [comment]
![image](https://github.com/user-attachments/assets/5f0906eb-5f15-44ba-ab86-a38ece300de8)
haha, I don't know whether this works, but on this site it says leaked

**Comment by Flamifly** [comment]
It is defintly way faster now like half a second
I checked the Password and It did not show red on the Chart so I am not sure if this works right at all or not

**Comment by FrozenAssassine** [comment]
Code seems good, so should work, we will see
