### ISSUE TITLE
Password safety chart not working properly

### ISSUE THREAD

**Issue by FrozenAssassine** [FrozenAssassine/EasePass#178]
![image](https://github.com/user-attachments/assets/1d667bc1-4a97-45aa-8bf7-0420a303eebb)

Why should the password aaaa contain numbers or even special characters. Pretty weird haha

**Comment by FrozenAssassine** [comment]
The password safety chart had wrong-positioned elements. The whole left side was mirrored. I was soo confused, but glad I came behind it 😂 

![image](https://github.com/user-attachments/assets/1e588470-e868-4d46-acef-b55a27002e61)

**Comment by Flamifly** [comment]
That seems defintly right to me😂
I do not see the Problem😂

**Comment by FrozenAssassine** [comment]
haha, should be fixed. Now the results make way more sense when typing there. But I am also not sure whether the ispwnd check still works
