### ISSUE TITLE
Web Requests

### ISSUE THREAD

**Issue by Flamifly** [FrozenAssassine/EasePass#182]
Why do we do Web Requests if the description is that we can use it offline.
Shouldn't we try to have every feature even if we are offline?

**Comment by FrozenAssassine** [comment]
Well we need web requests for three parts in the app:
- icon loading
- check for leaked passwords
- download plugins

All of those are not really needed for core functionality of the app. Also you can disable icons and leaked check. The plugins can be downloaded once and then you don't need an more internet connection.

So if you have better idea to do it without network connection, tell me. But as far as I know this is the best way so far?

**Comment by Flamifly** [comment]
So you could implement a Function that download the current leaked passwords of pwnd???.com or what the website is called.
I wouldn't do it instand because it's about 12gb.
I opened the Issue before I read how big it is so I think it won't be usefull to have a function like that

**Comment by finn-freitag** [comment]
You can also use Ease Pass offline. The three features mentioned by @FrozenAssassine are not available, but there are no errors that cause the app to crash.
