### ISSUE TITLE
Sort password list

### ISSUE THREAD

**Issue by FrozenAssassine** [FrozenAssassine/EasePass#2]
Add a feature to sort the password list

**Comment by finn-freitag** [comment]
Sorting in alphabetical order is ready, but reordering the items in the listbox by the user doesn't work.

**Comment by FrozenAssassine** [comment]
Try the following properties on the listview in XAML: 

CanDragItems="True" 
CanReorderItems="True" 
AllowDrop="True"
SelectionMode="Single"

**Comment by finn-freitag** [comment]
I have tried this before and it worked but it didn't update the order in the `ObservableCollection<PasswordManagerItem>`. (Even when I set `Mode=TwoWay`)

**Comment by FrozenAssassine** [comment]
It actually does update the Observable collection. I now call SaveData in the DragItemsCompleted event and then the sorted collection gets saved to the database.

**Comment by finn-freitag** [comment]
Ok I had tried exactly the same, and it had not worked. "It doesn't work on my machine!" ;-)

**Comment by FrozenAssassine** [comment]
Check the new commit and try it out.
