### ISSUE TITLE
Initialize screen width and height in ScreenScannerWindow

### ISSUE THREAD

**Issue by finn-freitag** [FrozenAssassine/EasePass#23]

**Comment by FrozenAssassine** [comment]
I found the following, maybe you try this to get the position and size of every screen

    foreach (Display display in Display.GetDisplays())
    {
        var pos = display.CurrentSetting.Position;
        var size = display.CurrentSetting.Resolution;
        
        Debug.WriteLine(pos.X + ":" + pos.Y + " " + size.Width + ":" + size.Height);
    }
