### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by FrozenAssassine** [FrozenAssassine/EasePass#3]
### Current progress:

- [x] C# Dialogs
- [x] C# UserControls
- [x] Xaml Pages
- [x] Info Messages 
- [x] Daily Tips
- [x] ManageDatabasePage
- [x] Clipboard Clear History Setting
- [x] Password generator
- [x] Tooltips

### Languages:

- [x] English
- [x] German

**Comment by FrozenAssassine** [comment]
- [ ] C# Dialogs
- [ ] C# UserControls
- [ ] Xaml Pages
- [ ] Info Messages

**Comment by finn-freitag** [comment]
Some translations doesn't fit into the controls.
![grafik](https://github.com/FrozenAssassine/EasePass/assets/126865059/003bf918-b480-4ca5-9dc6-d9614ccd31e9)
