### ISSUE TITLE
Show icons in the list with the starting character of the display name

### ISSUE THREAD

**Issue by FrozenAssassine** [FrozenAssassine/EasePass#31]
Show icons in the list with the starting character of the display name, when no website is given or the URL was not found.

Something like:
![Unbenannt-1](https://github.com/FrozenAssassine/EasePass/assets/72889252/7b7ae813-1961-4de2-ab6c-850502de47ad)

**Comment by finn-freitag** [comment]
Yeah, that's good! I also thought that if it is missing on some it looks silly, but I had no idea how to fix it. Yours is good.
