### ISSUE TITLE
Show icons button in settings does not affect anything

### ISSUE THREAD

**Issue by FrozenAssassine** [FrozenAssassine/EasePass#41]

**Comment by FrozenAssassine** [comment]
@finn-freitag What about removing the property to disable the icons, because with #31 it looks really good.

**Comment by finn-freitag** [comment]
Yes, it looks good, but maybe someone wants to turn off the online icons because of limited internet resources for example.

**Comment by FrozenAssassine** [comment]
But then there are still the awesome-looking generated icons

**Comment by finn-freitag** [comment]
Yes, maybe we remove the "Show icons" property and add a use internet property or something similar. But we can also leave it out altogether.

**Comment by FrozenAssassine** [comment]
The problem is, that I can not fix the bug mentioned in this issue 😂

**Comment by finn-freitag** [comment]
I will look for it.
