### ISSUE TITLE
Blink of the PasswordItem display controls  when loading PasswordPage 

### ISSUE THREAD

**Issue by FrozenAssassine** [FrozenAssassine/EasePass#98]

**Comment by finn-freitag** [comment]
I made this to load the PasswordSafetyChart template in CopyPasswordBox. It needs a better solution but this is the only one I found.

**Comment by FrozenAssassine** [comment]
Well as long as the PasswordSafetyChart works, we can let this happen and don't care as much currently. Then let's focus on the important things.
